#!/bin/bash

user=$1
GROUPE_MEDIA=multimedia
DOSSIER_MEDIA=/home/yunohost.multimedia

sudo mkdir -p "$DOSSIER_MEDIA/$user"
sudo mkdir -p "$DOSSIER_MEDIA/$user/Music"
sudo mkdir -p "$DOSSIER_MEDIA/$user/Picture"
sudo mkdir -p "$DOSSIER_MEDIA/$user/Video"
sudo mkdir -p "$DOSSIER_MEDIA/$user/Video/sous-dossier1"	# Dossier à définir
sudo mkdir -p "$DOSSIER_MEDIA/$user/Video/sous-dossier2"	# Dossier à définir
# Création du lien symbolique dans le home de l'utilisateur.
sudo ln -sf "$DOSSIER_MEDIA/$user" "/home/$user/Multimedia"
# Propriétaires des dossiers utilisateurs.
sudo chown -R $user:multimedia "$DOSSIER_MEDIA/$user"

## Application du setgid et du umask sur l'ensemble du dossier.
# Droits génériques sur les dossiers et fichiers: root:multimedia rwXrwsr-X
# Lecture/écriture éxecution (sur les dossiers) pour le propriétaire.
# Lecture/écriture setgid pour le groupe. Le setgid fixera le groupe pour tout nouveau fichier ou dossier créé.
# Lecture éxecution (sur les dossiers) pour les autres.
sudo chmod -R u=rwx,g=rwXs,o=rX "$DOSSIER_MEDIA/$user"
# Afin de garantir le droit d'écriture du groupe multimedia sur tout les fichiers créés. On place un ACL par défaut sur le groupe et sur other avec l'argument d.
sudo setfacl -R -m d:g:$GROUPE_MEDIA:rwX,o:r-X "$DOSSIER_MEDIA/$user"
