#!/bin/bash

user=$1
GROUPE_MEDIA=multimedia
DOSSIER_MEDIA=/home/yunohost.multimedia

sudo mkdir -p "$DOSSIER_MEDIA/$user"
sudo mkdir -p "$DOSSIER_MEDIA/$user/Music"
sudo mkdir -p "$DOSSIER_MEDIA/$user/Picture"
sudo mkdir -p "$DOSSIER_MEDIA/$user/Video"
sudo ln -sfn "$DOSSIER_MEDIA/share" "$DOSSIER_MEDIA/$user/Share"
# Création du lien symbolique dans le home de l'utilisateur.
sudo ln -sfn "$DOSSIER_MEDIA/$user" "/home/$user/Multimedia"
# Propriétaires des dossiers utilisateurs.
sudo chown -R $user "$DOSSIER_MEDIA/$user"

## Application des droits étendus sur le dossier multimedia.
# Droit d'écriture pour le groupe et le groupe multimedia en acl et droit de lecture pour other:
sudo setfacl -RnL -m g:$GROUPE_MEDIA:rwX,g::rwX,o:r-X "$DOSSIER_MEDIA/$user"
# Application de la même règle que précédemment, mais par défaut pour les nouveaux fichiers.
sudo setfacl -RnL -m d:g:$GROUPE_MEDIA:rwX,g::rwX,o:r-X "$DOSSIER_MEDIA/$user"
# Réglage du masque par défaut. Qui garantie (en principe...) un droit maximal à rwx. Donc pas de restriction de droits par l'acl.
sudo setfacl -RL -m m::rwx "$DOSSIER_MEDIA/$user"
